Que-1)Create a Numpy array of size 4 x 5.

In [ ]:
import numpy as np
array1=[1,2,3,4,5]
array2=[2,3,4,5,6]
array3=[3,4,5,6,7]
array4=[4,5,6,7,8]
npmatrix1=np.array([array1,array2,array3,array4])
print(npmatrix1)
print(type(npmatrix1))

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
<class 'numpy.ndarray'>



2) Randomly initialize the array.


In [ ]:
arr1=np.random.rand(4,4)
print(arr1)

[[0.37529036 0.89525733 0.78230509 0.06633995]
 [0.39883716 0.81428508 0.96811644 0.0382776 ]
 [0.18094077 0.09665101 0.09561043 0.7152129 ]
 [0.2619874  0.99065851 0.43487077 0.96997696]]


3) Get the Determinant and Transpose of the Matrix that you created.

In [ ]:
arr1=np.random.rand(4,4)
det = np.linalg.det(arr1)
print("Determinant is:-",int(det))
print("Transpose is:-",arr1.T)

Determinant is:- 0
Transpose is:- [[0.0549994  0.26094241 0.84261406 0.28068154]
 [0.35033226 0.08067163 0.04833034 0.9691399 ]
 [0.22277324 0.19919811 0.00475482 0.87244217]
 [0.65791817 0.37854977 0.25634002 0.34809103]]


4) Create another matrix of size 5 x 4 and randomly initialize it.

In [ ]:
arr1=np.random.rand(5,4)
print(arr1)

[[0.15794626 0.01881981 0.83664982 0.05342684]
 [0.84636525 0.78138364 0.96305075 0.2332578 ]
 [0.92528734 0.52949549 0.77470919 0.1847578 ]
 [0.35523097 0.10531743 0.18180933 0.98869642]
 [0.28406154 0.65286593 0.36085435 0.62291959]]


5) Perform Matrix multiplication.

In [ ]:
array1=[[1,2],[1,2]]
array2=[[2,3],[2,3]]
np.matmul(array1, array2)

array([[6, 9],
       [6, 9]])

6) Perform element wise matrix multiplication.

In [ ]:
array1=[1,2,3,4,5]
array2=[2,3,4,5,6]
np.multiply(array1,array2)

array([ 2,  6, 12, 20, 30])

7) Find mean, median of the numpy array created.

In [ ]:
print("Mean of whole matrix:-")
print(np.mean(npmatrix1))
print("Mean by column:-",np.mean(npmatrix1,axis=0))
print("Mean by column:-",np.mean(npmatrix1,axis=0))
print("Median is:-",np.median(npmatrix1))

Mean of whole matrix:-
4.5
Mean by column:- [2.5 3.5 4.5 5.5 6.5]
Mean by column:- [2.5 3.5 4.5 5.5 6.5]
Median is:- 4.5


8) Obtain each row in the second column of the first array.

In [ ]:
print(npmatrix1[:,2])

[3 4 5 6]


9) Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
data=pd.read_csv('drive/MyDrive/Iris.csv')
datam = data.iloc[:,:]
datam.mean()

Mounted at /content/drive


Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

10) Study about numpy array attributes and implement it on the first matrix.

In [3]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
arr1 = arr.shape
arr2 = arr.reshape(3,2)
print("arr1:\n",arr1)
print("arr2:\n",arr2)

arr1:
 (2, 3)
arr2:
 [[1 2]
 [3 4]
 [5 6]]
