### ***Linear regression model from scratch*** 

In [ ]:
import numpy as np
import torch

In [ ]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [ ]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [ ]:
inputs @ weight.t() + bias

tensor([[ 78.1855, -38.9552],
        [114.8458, -38.4361],
        [114.2791, -62.6583],
        [ 64.1535, -57.8251],
        [125.8019, -17.9175]], grad_fn=<AddBackward0>)

In [ ]:
def model(inputs):
    return inputs @ weight.t() + bias

In [ ]:
prediction = model(inputs)
print(prediction)

tensor([[208.2393, -36.5961],
        [270.7560, -45.8415],
        [372.1846, -46.3467],
        [174.1618, -49.4186],
        [273.4664, -35.5742]], grad_fn=<AddBackward0>)


### ***Loss function*** 

In [ ]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()

tensor(25180.4414, grad_fn=<DivBackward0>)

In [ ]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
loss = mse(prediction, targets)
print(loss)

tensor(25180.4414, grad_fn=<DivBackward0>)


### ***Compute gradients*** 

In [ ]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[ 15538.2031,  16746.6074,  10187.6045],
        [ -9906.7148, -11179.3145,  -6806.4561]])
tensor([ 183.5616, -118.9554])


### ***Train the model using gradient descent*** 

In [ ]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [ ]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(17030.2305, grad_fn=<DivBackward0>)


In [ ]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [ ]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(100.4828, grad_fn=<DivBackward0>)


In [ ]:
prediction

tensor([[ 57.8426,  59.9229],
        [ 73.9780,  82.3514],
        [136.3170, 113.9337],
        [ 24.8217,  36.0992],
        [ 85.2846,  93.5779]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])