### ***Linear regression using PyTorch built-ins*** 

#### ***Define DataLoader***

In [ ]:
import numpy as np
import torch

In [ ]:
# Targets (apples, oranges)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [ ]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]])
tensor([[ 22.,  37.],
        [119., 133.],
        [ 81., 101.],
        [ 56.,  70.],
        [103., 119.]])


#### ***nn.Linear***

In [ ]:
import torch.nn as nn

In [ ]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5306, -0.4632, -0.1616],
        [ 0.2526,  0.1122, -0.0674]], requires_grad=True)
Parameter containing:
tensor([-0.1764,  0.2934], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5306, -0.4632, -0.1616],
         [ 0.2526,  0.1122, -0.0674]], requires_grad=True),
 Parameter containing:
 tensor([-0.1764,  0.2934], requires_grad=True)]

In [ ]:
preds = model(inputs)
preds

tensor([[ -76.8939,   23.3515],
        [ -99.5659,   28.8389],
        [-117.7817,   33.3961],
        [ -80.1938,   28.3863],
        [ -92.5686,   23.7761]], grad_fn=<AddmmBackward0>)

#### ***loss functions***

In [ ]:
import torch.nn.functional as F

In [ ]:
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(18146.7109, grad_fn=<MseLossBackward0>)


#### ***Optimizer***

In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

#### ***Train for multiple epochs***

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 976.9943
Epoch [20/100], Loss: 428.5187
Epoch [30/100], Loss: 372.0293
Epoch [40/100], Loss: 330.4649
Epoch [50/100], Loss: 293.9655
Epoch [60/100], Loss: 261.7716
Epoch [70/100], Loss: 233.3673
Epoch [80/100], Loss: 208.3014
Epoch [90/100], Loss: 186.1765
Epoch [100/100], Loss: 166.6424


In [ ]:
prediction = model(inputs)
prediction

tensor([[ 60.7748,  74.8482],
        [ 83.1767,  98.9290],
        [110.6838, 129.6219],
        [ 42.0776,  62.6265],
        [ 91.3218, 101.2212]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[58.5609, 72.6601]], grad_fn=<AddmmBackward0>)